"""
Export API routes — Generate downloadable PDF and Markdown reports
from assessment data with full evidence traceability.
"""

from __future__ import annotations

import io
import json
from datetime import datetime
from typing import Optional

from fastapi import APIRouter, Query
from fastapi.responses import Response

from database import get_db
from knowledge_base.checklist_generator import get_maturity_model, calculate_maturity_score

router = APIRouter()


LEVEL_NAMES = ["", "Exploring", "Experimenting", "Operationalizing", "Scaling", "Transforming"]


def _generate_markdown(
    score_result: dict,
    assessments: dict,
    roadmap_items: list | None = None,
) -> str:
    """Generate a formatted Markdown report."""
    model = get_maturity_model()
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = [
        f"# AI Strategy Hub — AI Maturity Assessment Report",
        f"",
        f"**Generated:** {now}  ",
        f"**Model Version:** {model.version}  ",
        f"**Overall Score:** {score_result.get('overall_score', 0):.1f} / 100  ",
        f"**Maturity Level:** {LEVEL_NAMES[score_result.get('overall_level', 1)]} (Level {score_result.get('overall_level', 1)})",
        f"",
        f"---",
        f"",
        f"## Dimension Scores",
        f"",
        f"| Dimension | Score | Level | Fulfilled |",
        f"|-----------|-------|-------|-----------|",
    ]

    for ds in score_result.get("dimension_scores", []):
        level_name = LEVEL_NAMES[ds.get("level", 1)]
        lines.append(
            f"| {ds['icon']} {ds['dimension_name']} | {ds['score']:.1f}% | {level_name} | {ds['fulfilled_count']}/{ds['total_count']} |"
        )

    # Strengths & Gaps
    lines.extend(["", "---", "", "## Strengths", ""])
    for s in score_result.get("strengths", []):
        lines.append(f"- {s}")
    if not score_result.get("strengths"):
        lines.append("- No strengths identified yet")

    lines.extend(["", "## Gaps", ""])
    for g in score_result.get("gaps", []):
        lines.append(f"- {g}")
    if not score_result.get("gaps"):
        lines.append("- No gaps identified")

    # Detailed checkpoint status
    lines.extend(["", "---", "", "## Detailed Checkpoint Status", ""])

    for dim in model.dimensions:
        lines.extend([f"### {dim.icon} {dim.name}", ""])
        for cp in dim.checkpoints:
            a = assessments.get(cp.id, {})
            status = "✅" if a.get("fulfilled", False) else "⬜"
            sources_str = ", ".join(
                f"`{tag.source}: {tag.reference}`"
                for tag in cp.evidence_tags
            ) if cp.evidence_tags else ", ".join(f"`{s}`" for s in cp.sources)
            lines.append(f"- {status} **{cp.id}** — {cp.text}")
            lines.append(f"  - Sources: {sources_str}")
        lines.append("")

    # Roadmap (if provided)
    if roadmap_items:
        lines.extend(["---", "", "## Prioritized Roadmap", ""])
        lines.append("| Priority | Checkpoint | Dimension | Effort | Sources |")
        lines.append("|----------|-----------|-----------|--------|---------|")
        for item in roadmap_items[:20]:
            sources = ", ".join(f"{t['source']}" for t in item.get("evidence_tags", []))
            lines.append(
                f"| {item.get('priority_score', 0):.0f} | {item['checkpoint_text'][:60]}… | {item['dimension_icon']} {item['dimension_name']} | {item['effort']} | {sources[:40]} |"
            )
        lines.append("")

    lines.extend([
        "---",
        "",
        f"*Report generated by AI Strategy Hub*",
        f"*Based on: NIST AI RMF, EU AI Act, Google AI Adoption Framework, Microsoft RAI MM, OWASP AI Security, UNESCO AI Readiness*",
    ])

    return "\n".join(lines)


def _generate_pdf_bytes(
    score_result: dict,
    assessments: dict,
) -> bytes:
    """Generate a PDF report using reportlab."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        )
    except ImportError:
        # Fallback: return markdown as PDF-like text
        md = _generate_markdown(score_result, assessments)
        return md.encode("utf-8")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Title"], fontSize=20, spaceAfter=12)
    heading_style = ParagraphStyle("Heading", parent=styles["Heading2"], fontSize=14, spaceAfter=8)
    body_style = styles["BodyText"]

    elements = []

    # Title
    elements.append(Paragraph("AI Strategy Hub — AI Maturity Assessment Report", title_style))
    elements.append(Paragraph(
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} | "
        f"Score: {score_result.get('overall_score', 0):.1f}/100 | "
        f"Level: {LEVEL_NAMES[score_result.get('overall_level', 1)]}",
        body_style
    ))
    elements.append(Spacer(1, 20))

    # Dimension scores table
    elements.append(Paragraph("Dimension Scores", heading_style))
    table_data = [["Dimension", "Score", "Level", "Fulfilled"]]
    for ds in score_result.get("dimension_scores", []):
        table_data.append([
            f"{ds['icon']} {ds['dimension_name']}",
            f"{ds['score']:.1f}%",
            LEVEL_NAMES[ds.get("level", 1)],
            f"{ds['fulfilled_count']}/{ds['total_count']}",
        ])

    table = Table(table_data, colWidths=[7*cm, 3*cm, 4*cm, 3*cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1f36")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#2a2f46")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#0c1021"), colors.HexColor("#111631")]),
        ("TEXTCOLOR", (0, 1), (-1, -1), colors.HexColor("#e8eaf6")),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 20))

    # Strengths & Gaps
    elements.append(Paragraph("Strengths", heading_style))
    for s in score_result.get("strengths", [])[:5]:
        elements.append(Paragraph(f"• {s}", body_style))
    elements.append(Spacer(1, 10))

    elements.append(Paragraph("Gaps", heading_style))
    for g in score_result.get("gaps", [])[:5]:
        elements.append(Paragraph(f"• {g}", body_style))
    elements.append(Spacer(1, 10))

    # Footer
    elements.append(Spacer(1, 30))
    elements.append(Paragraph(
        "Report generated by AI Strategy Hub. "
        "Based on: NIST AI RMF, EU AI Act, Google AI Adoption Framework, "
        "Microsoft RAI MM, OWASP AI Security, UNESCO AI Readiness.",
        ParagraphStyle("Footer", parent=body_style, fontSize=7, textColor=colors.grey),
    ))

    doc.build(elements)
    return buffer.getvalue()


@router.post("/markdown")
async def export_markdown(
    assessment_id: Optional[str] = Query(default=None),
):
    """Export assessment results as a Markdown document."""
    db = await get_db()
    try:
        if assessment_id:
            cursor = await db.execute(
                "SELECT * FROM manual_assessments WHERE id = ?", (assessment_id,)
            )
        else:
            cursor = await db.execute(
                "SELECT * FROM manual_assessments ORDER BY created_at DESC LIMIT 1"
            )
        row = await cursor.fetchone()
    finally:
        pass  # singleton connection, no close needed

    if not row:
        # Generate empty report with no assessments
        from knowledge_base.checklist_generator import calculate_maturity_score
        score_result = calculate_maturity_score({})
        assessments = {}
    else:
        assessments = json.loads(row["assessments"])
        score_result = {
            "overall_score": row["overall_score"],
            "overall_level": row["overall_level"],
            "dimension_scores": json.loads(row["dimension_scores"]),
            "strengths": json.loads(row["strengths"]),
            "gaps": json.loads(row["gaps"]),
        }

    md_content = _generate_markdown(score_result, assessments)

    return Response(
        content=md_content,
        media_type="text/markdown",
        headers={
            "Content-Disposition": f"attachment; filename=ai_strategy_hub_report_{datetime.now().strftime('%Y%m%d')}.md"
        },
    )


@router.post("/pdf")
async def export_pdf(
    assessment_id: Optional[str] = Query(default=None),
):
    """Export assessment results as a PDF document."""
    db = await get_db()
    try:
        if assessment_id:
            cursor = await db.execute(
                "SELECT * FROM manual_assessments WHERE id = ?", (assessment_id,)
            )
        else:
            cursor = await db.execute(
                "SELECT * FROM manual_assessments ORDER BY created_at DESC LIMIT 1"
            )
        row = await cursor.fetchone()
    finally:
        pass  # singleton connection, no close needed

    if not row:
        from knowledge_base.checklist_generator import calculate_maturity_score
        score_result = calculate_maturity_score({})
        assessments = {}
    else:
        assessments = json.loads(row["assessments"])
        score_result = {
            "overall_score": row["overall_score"],
            "overall_level": row["overall_level"],
            "dimension_scores": json.loads(row["dimension_scores"]),
            "strengths": json.loads(row["strengths"]),
            "gaps": json.loads(row["gaps"]),
        }

    pdf_bytes = _generate_pdf_bytes(score_result, assessments)

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f"attachment; filename=ai_strategy_hub_report_{datetime.now().strftime('%Y%m%d')}.pdf"
        },
    )


from pydantic import BaseModel
import os
from fastapi import HTTPException

class BriefingRequest(BaseModel):
    score_data: dict

@router.post("/executive-briefing")
async def generate_executive_briefing(request: BriefingRequest):
    """Generate an AI-narrated Executive Summary based on assessment scores."""
    gemini_key = os.getenv("GEMINI_API_KEY", "")
    if not gemini_key:
        raise HTTPException(status_code=500, detail="GEMINI_API_KEY not configured")

    try:
        import google.generativeai as genai
        genai.configure(api_key=gemini_key)
        model = genai.GenerativeModel("gemini-3.1-pro-preview")

        scores = request.score_data
        overall_score = scores.get("overall_score", 0)
        overall_level = scores.get("overall_level", 1)
        gaps = "\\n- ".join(scores.get("gaps", [])[:7])
        strengths = "\\n- ".join(scores.get("strengths", [])[:3])

        prompt = f"""You are a top-tier Management Consultant (McKinsey/BCG level). 
Write an 'Executive Summary & AI Readiness Narrative' for a CEO based on this AI Strategy Hub Maturity Assessment:
- Overall Score: {overall_score:.1f}/100 (Level {overall_level})
- Key Strengths: 
- {strengths}
- Critical Gaps & Risks:
- {gaps}

Provide a structured, beautifully formatted Markdown response with:
1. **Executive Summary** (1-2 paragraphs summarizing the posture)
2. **Key Strategic Risks** (Highlighting the biggest gaps translated to business risk)
3. **Top 3 Strategic Priorities** (Actionable next steps)

Keep the tone professional, urgent but optimistic, and highly actionable. Return ONLY Markdown."""

        response = model.generate_content(
            prompt,
            generation_config=genai.GenerationConfig(temperature=0.3)
        )
        return {"markdown": response.text}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate briefing: {e}")

